### ISSUE TITLE
About the matte images

### ISSUE THREAD

**Issue by fl82hope** [naoto0804/SynShadow#1]
Great job! Congradulations!

For the matte images, I could not get the download link after clicking it. When they will be available? Thanks a lot.

**Comment by fl82hope** [comment]
I am going to use for academic purpose, my email is lanf@email.sc.edu, if ok, could you share me with email?

**Comment by naoto0804** [comment]
Please try
```
$ wget <URL_of_the_dataset>
```
, for example, or some other alternative ways to **directly download** the dataset from the URL.
