### ISSUE TITLE
Shadow detect error

### ISSUE THREAD

**Issue by clannadcl** [naoto0804/SynShadow#10]
I have downloaded the he models for shadow [detection,](http://www.hal.t.u-tokyo.ac.jp/~inoue/projects/synthetic_shadow/trained_models/detection/det_dsd_synshadow.zip) and put i into ./checkpoints.
When I run:
`python test.py --dataset_mode demo --model detect --netG dsd --dataset_root ../Samples/ `
I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/SynShadow-main/src/models/n
etworks/base/resnext/resnext_101_32x4d.pth'

How to infer an image.

**Comment by naoto0804** [comment]
Could you copy and paste the full stack trace here? Currently, I'm not 100% certain in which function the error is raised.

**Comment by clannadcl** [comment]
Traceback (most recent call last):                                                                                                   
  File "test.py", line 21, in <module>                                                                                               
    model = create_model(opt)                                                                                                        
  File "/SynShadow-main/src/models/__init__.py", line 36, in create_model            
    instance = model(opt)                                                                                                            
  File "/SynShadow-main/src/models/detect_model.py", line 98, in __init__            
    super().__init__(opt)                                                                                                            
  File "SynShadow-main/src/models/base_model.py", line 21, in __init__              
    self.netG, self.netD = self.initialize_networks(opt)                                                                             
  File "/SynShadow-main/src/models/base_model.py", line 82, in initialize_networks   
    netG = networks.define_G(opt)                                                                                                    
  File "/SynShadow-main/src/models/networks/__init__.py", line 44, in define_G       
    return create_network(netG_cls, opt)                                                                                             
  File "SynShadow-main/src/models/networks/__init__.py", line 33, in create_network 
    net = cls(opt)                                                                                                                   
  File "/SynShadow-main/src/models/networks/detection/zheng_cvpr2019_dsdnet.py", line
 65, in __init__                                                                                                                     
    resnext = ResNeXt101()                                                                                                           
  File "/SynShadow-main/src/models/networks/base/resnext/resnext101_regular.py", line
 17, in __init__                                                                                                                     
    weights = torch.load(backbone_path)                                                                                              
  File "/lib/python3.8/site-packages/torch/serialization.py", line 571, in load  
    with _open_file_like(f, 'rb') as opened_file:                                                                                    
  File "mm-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 229, in _open_
file_like                                                                                                                            
    return _open_file(name_or_buffer, mode)                                                                                          
  File "mm-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 210, in __init
__                                                                                                                                   
    super(_open_file, self).__init__(open(name, mode))                                                                               
FileNotFoundError: [Errno 2] No such file or directory: 'SynShadow-main/src/models/n
etworks/base/resnext/resnext_101_32x4d.pth'

**Comment by naoto0804** [comment]
Seems I guessed right. Could you manually download the weight from [here](https://drive.google.com/file/d/1EDUcaGNiakWO9Xvk9kWgkkcnTYZ6VQoT/view) and put it under `src/models/networks/base/resnext` ?

**Comment by naoto0804** [comment]
Maybe [this part](https://github.com/naoto0804/SynShadow/blob/main/src/models/networks/base/resnext/resnext101_regular.py#L11-L20) should have raised warning when there is no weight file. Anyway, thanks for reporting the detailed errors!!

**Comment by naoto0804** [comment]
If you still have a question, please let me know!
