### ISSUE TITLE
About Synthetic shadow

### ISSUE THREAD

**Issue by GuoLanqing** [naoto0804/SynShadow#15]
Thanks for your great work. Could you please provide an complete instruction for synthetic dataset generation? A little confusing about the darken function. I don't find the definition of the parameter "opt.intercepts_mode".

Thank you~

**Comment by naoto0804** [comment]
Thank you for your interest in our project! For a quick answer, always use `affine` for `intercepts_mode`. Other modes are just for the ablation study for configuring the shadow model in Table 3 of the paper.
(Let me know if you want a very detailed one;)
