### ISSUE TITLE
why this error is happening

### ISSUE THREAD

**Issue by s2g7a03** [naoto0804/SynShadow#17]
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    for i, data_i in enumerate(dataloader, start=iter_counter.epoch_iter):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/SynShadow/src/data/synth_dataset.py", line 44, in __getitem__
    mask_index = next(self.mask_iter)
  File "/content/SynShadow/src/data/util.py", line 9, in InfiniteSampler
    yield order[i]
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by naoto0804** [comment]
I guess the dataset directory (set by `--dataset_root`) is not correctly specified. Since there are many types of files (shadow, shadow-free, mask). Please refer [datasets#file-organization](https://github.com/naoto0804/SynShadow/tree/main/datasets#file-organization) and strictly follow the instruction. If it doesn't solve your situation. Let me know (with some detailed info. on execution, such as where the script is launched)

**Comment by sga2703** [comment]
![Screenshot_20230306_084758](https://user-images.githubusercontent.com/127030693/223012059-f49cb6d1-7bc3-40b1-86f3-1b58d009ad52.png)
In SynShadow/matte folder what should i need to upload

**Comment by naoto0804** [comment]
Thank you! Hmm.. 
I had tried some typical mistakes but did not reproduce the errors above.
Could you attach the *entire* log (in a single file) and show the actual commands to launch the train.py?

**Comment by naoto0804** [comment]
Have you downloaded our SynShadow dataset as [instructed](https://github.com/naoto0804/SynShadow/blob/main/datasets/README.md#overview)?

**Comment by sga2703** [comment]
its resolved after i upload to the matte folder

BUT what should be uploaded there

**Comment by sga2703** [comment]
> Have you downloaded our SynShadow dataset as [instructed](https://github.com/naoto0804/SynShadow/blob/main/datasets/README.md#overview)?

matte images link is not working there

**Comment by naoto0804** [comment]
Just clicking the link may not 'work' but you might copy the link address. I can download it now by 
``` bash
wget http://www.hal.t.u-tokyo.ac.jp/~inoue/projects/synthetic_shadow/SynShadow.zip
```
If this or alternative commands do not work, let me know

**Comment by sga2703** [comment]
its working now, Thank you...
where we can see the image with synthetic shadow

**Comment by naoto0804** [comment]
[This part](https://github.com/naoto0804/SynShadow/blob/main/src/data/synth_dataset.py#L63-L65) does the composition. Please read the file carefully and try to get what you want. I'm busy and may not answer questions that cost too much time to understand or inspect, especially if they seem to be asked before thinking on your own; sorry in advance.
