### ISSUE TITLE
SynShadow dataset download address is disabled

### ISSUE THREAD

**Issue by Tangyuan-X** [naoto0804/SynShadow#19]
- [Matte images](http://www.hal.t.u-tokyo.ac.jp/~inoue/projects/synthetic_shadow/SynShadow.zip) for SynShadow，This address is invalid，Can you add a new download address? Thank you very much
- 
![image](https://github.com/naoto0804/SynShadow/assets/56478488/56806cac-f1a1-496a-a899-138f750b8a7d)

**Comment by naoto0804** [comment]
Hi, I've moved all the resources to Google Drive. Please download the data from [here](https://drive.google.com/file/d/1RErNUbkstaiCchYzbe8wPYTEdU-Yp7o0/view?usp=drive_link).
