### ISSUE TITLE
no DHAN training code

### ISSUE THREAD

**Issue by nachifur** [naoto0804/SynShadow#5]
Hello, your work is very exciting, thank you for your contribution to this field.
There is no training code for DHAN. I would like to know further details about DHAN under the setting of SynShadow->ISTD+. 
Can you provide the corresponding code? I saw the evaluation results in the paper. 
Thank you for your work and look forward to your reply.

**Comment by naoto0804** [comment]
Thanks for visiting this repo! 
Since I was not able to correctly re-implemement DHAN on this repo on PyTorch, I modified the original [code](https://github.com/vinthony/ghost-free-shadow-removal) in Tensorflow to use tiplets generated on-the-fly [here](https://github.com/naoto0804/SynShadow/blob/main/src/data/synth_dataset.py);

**Comment by nachifur** [comment]
Thank you for your prompt reply. And thank you again for your code.

**Comment by naoto0804** [comment]
Sorry not to make that part of the code available;

**Comment by nachifur** [comment]
Can you upload your modified DHAN code? Even if it is not pytorch, it's OK. I want to see the complete code about DHAN training process, which is very important to me. I want to reproduce the following results: 
`SynShadow->ISTD+ | ISTD+ | 4.6 | `
`SynShadow->SRD+ | SRD+ | 6.6| `
Thank you for your work and look forward to your reply.

**Comment by naoto0804** [comment]
Instead of [this part](https://github.com/vinthony/ghost-free-shadow-removal/blob/master/train_sr.py#L121-L140), I made the triplets by
```
    for epoch in range(1,maxepoch):
        input_images_ids,target_images_ids=[None]*num_train,[None]*num_train
        epoch_st = time.time()

        if os.path.isdir("%s/%04d"%(task,epoch)):
            continue
        cnt=0
        # for id in np.random.permutation(num_train):
        for id, data_i in enumerate(dataloader):  # <- this is dataloader instance used in PyTorch
            st=time.time()
            if input_images_ids[id] is None:
                running_idx = (epoch-1)*num_train+cnt

                def convert(x):
                    x = x.numpy().transpose([0, 2, 3, 1])  # (B, H, W, C)
                    x = x[..., ::-1]  # RGB -> BGR
                    return x

                iminput = convert(data_i['input'])
                imtarget = convert(data_i['target'])
                maskgt = convert(data_i['mask'])
```
