### ISSUE TITLE
Matte images fixed size

### ISSUE THREAD

**Issue by MohammedElGharawy** [naoto0804/SynShadow#8]
Hello, Thanks for sharing your work

Is it possible to change the size of the matte images? 

Or are they restricted to 256*256by design?

**Comment by MohammedElGharawy** [comment]
Here's the exact command i used 
!python test.py --dataset_mode demo --dataset_root datapath  --mask_to_G precomp_mask --mask_to_G_thresh 0.95

**Comment by naoto0804** [comment]
If you train the network with different resolution. Since the network of SP+M Net is mostly fully convolutional, you should modify a single part [here](https://github.com/naoto0804/SynShadow/blob/main/src/models/networks/removal/le_iccv2019_spmnet.py#L17-L18), since you will 'flatten' the feature map, whose size is dependent of the input resolution.

**Comment by MohammedElGharawy** [comment]
I just used the dataset demo feature to test on multiple images I had with different resolutions (1520 * 912) but all their output was fixed at 256 * 256.
Do I need to retrain the network to get a different resolution for the output?!

**Comment by naoto0804** [comment]
My comment above may be wrong. Sorry for my misunderstanding.

As the [original paper](https://www3.cs.stonybrook.edu/~cvl/projects/SID/index.html) suggests, the easiest way to process arbitrary size input images is 'interpolating the shadow matte', though the performance may be a bit worse than the model tuned for a specific resolution,

**Comment by MohammedElGharawy** [comment]
I see, but is there a way in the code existing in this repo to change the output size for the shadow-free image and the matte output?

**Comment by MohammedElGharawy** [comment]
I want to use the pretrained model as it is and get an output with the same resolution as the input basically.

**Comment by naoto0804** [comment]
Unfortunately, the code is not included in this repository due to the cost of refactoring;
Basically, you might modify [here](https://github.com/naoto0804/SynShadow/blob/main/src/models/networks/removal/le_iccv2019_spmnet.py#L126-L132)

```
    def forward(self, rgb, mask):
        rgb_lr = downsample(rgb)
        mask_lr = downsample(mask)
        w, b = self.spnet(rgb_lr, mask_lr)

        lit = self.relit(rgb, w, b)
        lit_lr = downsample(lit)
        matte_lr = self.mnet([rgb_lr, lit_lr, mask_lr])
        matte = upsample(matte_lr)
        result = self.compose(rgb, lit, matte)
```

**Comment by naoto0804** [comment]
[This part](https://github.com/naoto0804/SynShadow/blob/main/src/test.py#L66-L80) should be what you want; You might want to modify [dataloader part](https://github.com/naoto0804/SynShadow/blob/main/src/data/paired_dataset.py#L77-L80) to keep the given image in the original resolution as PyTorch tensor format.
